spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/forumhub
    username: samuel
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: samuel
      password: ${DB_PASSWORD}
server:
  error:
    include-stacktrace: never
api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

